### ISSUE TITLE
Крэш после логаута

### ISSUE THREAD

**Issue by khramtsoff** [allychat/android-sdk#4]
1. Авторизуюсь в приложении, подключаюсь к чату
2. Выключаю экран, жду таймаут
3. Включаю экран, происходит разлогаут, вызываю AllyChat.getInstance().close();
   приложение падает в loop чата (libraryRealmConfig == null):

"networkOperation@5529" prio=10 runnable
  java.lang.Thread.State: RUNNABLE
      at io.realm.Realm.getInstance(Realm.java:211)
      at com.sergeymild.chat.AllyChat.getRealm(AllyChat.java:98) // здесь libraryRealmConfig == null
      at com.sergeymild.chat.utils.AllyChatPreferences.setUser(AllyChatPreferences.java:152)
      at com.sergeymild.chat.AllyChat$2.run(AllyChat.java:232)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at com.sergeymild.chat.utils.DispatchQueue.run(DispatchQueue.java:138)

может есть идеи? если нет, позже попробую воспроизвести в демо проекте

**Comment by khramtsoff** [comment]
Как знал, что не надо спешить с багом :-)
При выходе из background, происходит подключение AllyChat.build, дальше разлогаут вызывает AllyChat.getInstance().close(), а после подключения запускается runnable, хотя этого AllyChat'a уже нет. Можно закрывать
